format_version: 10
pipelines:
  tic-tac-toe-pipeline:
    group: My-Pipelines
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-33a4d40:
        git: https://github.com/rajeshgoyalg/github-actions-for-packages
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
    - tic-tac-toe-stage:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          hello-world:
            timeout: 0
            tasks:
            - exec:
                command: pwd
                run_if: passed
            - exec:
                command: ls
                run_if: passed
            - exec:
                arguments:
                - status
                command: git
                run_if: passed
